### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by shahrilnet** [kernel1024/qmanga#1]
Can you make the binary release for this project? :D

**Comment by kernel1024** [comment]
Yep, I can make i686 and x64 releases for Linux with dynamic linking - [v1.0.0](https://github.com/kernel1024/qmanga/releases/tag/v1.0.0)

**Comment by kernel1024** [comment]
I have added first release with source and binary, compiled for amd64 architecture. Binary dependencies from Archlinux distribution snapshot at 2016/12/10.

Some libraries updates very often, such as poppler, ICU, imagemagick with ABI / library filename changes, which breaks binary dependencies.
I recommend to compile from sources. Run qmake, make, then just run qmanga binary from sources directory, no installation needed.

**Comment by kernel1024** [comment]
Compiled windows 32bit binary with all necessary dlls. [v1.1.0](https://github.com/kernel1024/qmanga/releases/tag/v1.1.0) in release section.
