### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by ryll-spectre** [kernel1024/qmanga#2]
Hey kernal1024, is there any way I could contact you to ask you a few questions about this manga reader?

**Comment by kernel1024** [comment]
Yes, you can ask right here.

**Comment by ryll-spectre** [comment]
I'm trying to create a manga reader myself from scratch to learn Qt, but I'm having a problem which I think you might've solved in your own project.

I want the image to fit the QLabel/QScrollArea automatically when it is opened by the user. Not stretched out to fit the whole screen, but I want the top of the image to meet the top of the GUI screen and the bottom of the image to meet the bottom of the GUI screen.  It would also need to be dynamically resized whenever the user makes the GUI application larger or smaller.  [This](https://d2.alternativeto.net/dist/s/windows-photo-viewer_234658_full.jpg?format=jpg&width=1600&height=1600&mode=min&upscale=false) is actually a good example of how I want the manga images to be displayed.

Right now, all I'm doing is setting a Pixmap on my QLabel from a QImage, as you can see [here](https://github.com/jjgccg/nikui/blob/211d20d9446aa8b0996000ecfb9fe7e88fc548ca/nikui.cpp#L113).  It automatically sets a scroll bar because the manga images are so large (instead of resizing it to fit the top and bottom margins of the QLabel, as I've described above).

I've done a lot of research on this issue, but can't seem to find a solution.  Did you do anything specific to tackle this problem?

**Comment by kernel1024** [comment]
For "fit page" zoom mode i just scale image to widget size by hand [here](https://github.com/kernel1024/qmanga/blob/90dca3c37368710c602de8477cf21bf7637f2991/zmangaview.cpp#L538), forcing page redraw/rescale on window resize event. 
For other zoom modes (width, height, original) - creating big image and using QScrollArea as scroll area.

I tried to use QLabel as display widget for manga page in early builds, but now i use QWidget with custom paintEvent with image scaling code and QScrollArea.

Also, another option - custom QWidget with paintEvent, resizeEvent, etc and static scrollbars, without QScrollArea. Zoom and pan handling - in that custom widget. I think, this is more clear aproach.

**Comment by ryll-spectre** [comment]
Could you explain that last option a bit more?  I'm not quite understanding.

**Comment by ryll-spectre** [comment]
Kernal, no worries, I think I've found an alternative way of doing things.  I'm scaling the QPixmap to be the same height and width as the QLabel whenever an image is originally opened for the first time while maintaining the aspect ratio.

Then, the image is reset with a new width and height whenever zooming in and zooming out takes place.  Because the image is reset, it never becomes blurry if trying to zoom in.

```
    currentImage = newImage;
    QPixmap pixmap = QPixmap::fromImage(currentImage);

    imageLabel->clear();
    imageLabel->setPixmap(pixmap.scaled(width() * widthFactor, height() * heightFactor, Qt::KeepAspectRatio, Qt::SmoothTransformation));
```

Zooming in and out both change the "widthFactor" and "heightFactor" by some amount.

```
void Nikui::zoomIn()
{
    widthFactor *= 1.25;
    heightFactor *= 1.25;
    scaleImage(1.25);
}

void Nikui::zoomOut()
{
    widthFactor *= .9;
    heightFactor *= .9;
    scaleImage(0.9);
}
```

The image is just reset based on these private members.  Whenever a user opens new images in the current session, it is set to be the same exact width and height as the previous images because the private members have maintained state.

Not sure if this is the best way to do things, but it's working for now.  I should just now need to check for a window resizing event, which will reset the image again using the code above.  So that's the next step.
